language: ruby
rvm:
  - "2.0.0"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: "rake ci"

bundler_args: --without headless

before_install:
  - gem install bundler
  - sudo apt-get install libclamav-dev libclamav6 clamav clamav-base clamav-daemon clamav-freshclam clamav-unofficial-sigs
  - gem install clamav
  - sudo freshclam

branches:
  only:
    - master
    - develop
    - release
    - sandbox

env:
  matrix:
    - SPEC_GROUP=2
    - SPEC_GROUP=1
    - SPEC_GROUP=0
